include: package:flutter_lints/flutter.yaml

linter:
    rules:
        avoid_print: false
        parameter_assignments: true
        prefer_single_quotes: true
        missing_return: true
        always_declare_return_types: true
        avoid_void_async: true
        use_build_context_synchronously: false
        prefer_relative_imports: true
        sort_child_properties_last: true

analyzer:
    strong-mode:

    errors:
        missing_required_param: error
        parameter_assignments: error
        missing_return: error
        invalid_annotation_target: ignore
    exclude:
        - "**/*.g.dart"
        - "**/*.freezed.dart"
