name: teamtalkapp
description: TeamTalk application for Empact.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.18.2 <3.0.0"

dependencies:
    auto_route: ^5.0.2
    cupertino_icons: ^1.0.2
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    flutter_svg: ^1.1.6
    google_fonts: ^3.0.1
    hooks_riverpod: ^2.1.1
    intl: ^0.17.0
    material_design_icons_flutter: ^5.0.6996
    shared_preferences: ^2.0.15
    carousel_slider: ^4.1.1

dev_dependencies:
    auto_route_generator: ^5.0.3
    build_runner: ^2.3.2
    flutter_gen_runner: ^5.1.0+1
    flutter_launcher_icons: ^0.10.0
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter
    freezed: ^2.2.1

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/icons/
        - assets/dev/

flutter_gen:
    integrations:
        flutter_svg: true
